### ISSUE TITLE
No calendar shown

### ISSUE THREAD

**Issue by juvenalandres** [nagimov/agendav-docker#6]
Hello, 
I'm trying your container to connect it to my Baikal instance. When accessing the web interface with one of the Users created in Baikal, it does not show any calendar at all, just this:

![image](https://user-images.githubusercontent.com/18738412/174766980-62fa5f08-62e8-473e-a609-4313f20d3f29.png)

The logs show this warning, what does it mean? That IP is not my localhost
```
...@patxi:/var/lib/docker/calendar# docker logs agendav
Stopping MariaDB database server: mysqld.
Starting MariaDB database server: mysqld . . . . . . . . . . . . . . . . ..
Start webserver
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.240.4. Set the 'ServerName' directive globally to suppress this message
```

My docker-compose looks like this:

```
agendav:
    image: nagimov/agendav-docker:latest
    container_name: agendav
    environment:
      - AGENDAV_SERVER_NAME=127.0.0.1
      - AGENDAV_TITLE=Bienvenido a tu calendario
      - AGENDAV_FOOTER=Hosted by Madriguerasb
      - AGENDAV_ENC_KEY=****
      - AGENDAV_CALDAV_SERVER=https://****/cal.php
      - AGENDAV_TIMEZONE=UTC+1
      - AGENDAV_LANG=en
      - AGENDAV_LOG_DIR=/tmp/
    ports:
      - "88:80"
```

Any help would be appreciated.

Thank you

**Comment by nagimov** [comment]
Could you post your `docker run` command or `docker-compose.yml` for baikal, and screenshots of initial baikal setup (you might need to re-create your baikal container)

**Comment by juvenalandres** [comment]
Thanks for getting back to me. This is my complete `docker-compose.yaml`

```
version: "3"
services:
  baikal:
    image: ckulka/baikal:nginx
    restart: always
    ports:
      - "86:80"
    volumes:
      - /srv/dev-disk-by-uuid-b25ef428-93bd-416b-996e-2d308bee1897/data/appdata/baikal/config:/var/www/baikal/config
      - /srv/dev-disk-by-uuid-b25ef428-93bd-416b-996e-2d308bee1897/data/appdata/baikal/data:/var/www/baikal/Specific
    links:
      - baikal-db
      
  baikal-db:
       restart: always
       image: mariadb
       container_name: baikal-db
       volumes:
            - /srv/dev-disk-by-uuid-b25ef428-93bd-416b-996e-2d308bee1897/data/appdata/baikal/db:/var/lib/mysql
       environment:
            MYSQL_ROOT_PASSWORD: xxxx
            MYSQL_DATABASE: baikal
            MYSQL_USER: baikal
            MYSQL_PASSWORD: xxxx


  agendav:
    image: nagimov/agendav-docker:latest
    container_name: agendav
    environment:
      - AGENDAV_SERVER_NAME=127.0.0.1
      - AGENDAV_TITLE=Bienvenido a tu calendario
      - AGENDAV_FOOTER=Hosted by Madriguerasb
      - AGENDAV_ENC_KEY=xxxx
      - AGENDAV_CALDAV_SERVER=https://cal.xxxx.com/cal.php
      - AGENDAV_TIMEZONE=UTC+1
      - AGENDAV_LANG=en
      - AGENDAV_LOG_DIR=/tmp/
    ports:
      - "88:80"
```

Here are the screenshots of the setup of Baikal

![image](https://user-images.githubusercontent.com/18738412/174965882-87f19b52-ff0e-49f2-9150-3e321f4df83f.png)

![image](https://user-images.githubusercontent.com/18738412/174965952-c04bc375-30d5-4f1d-b359-714eebbbf26f.png)

Cheers
